### ISSUE TITLE
Component showing incorrectly

### ISSUE THREAD

**Issue by josh345ag** [MikaelEdebro/vue-airbnb-style-datepicker#65] opened 2018-11-03 01:17 UTC
The component is showing incorrectly.
<img width="596" alt="bug" src="https://user-images.githubusercontent.com/44032019/47946640-183bfc80-deed-11e8-82e0-8b43d6519e58.png">

**Comment by MikaelEdebro** [comment] 2018-11-16 21:00
What browser are you using?
Are you using some CSS lib that might be conflicting with the CSS?

**Comment by JohnyProkie** [comment] 2018-12-01 21:38
Hi, I have the very same problem. Looks like changing 
`.asd__wrapper{ text-align: center; } `
to 
`.asd__wrapper{ text-align: right; }`
fix the issue

**Comment by MikaelEdebro** [comment] 2018-12-02 10:14
Could you share some link where this is reproduced? Most likely, there is some CSS interfering with the component.

**Comment by JohnyProkie** [comment] 2018-12-08 18:43
I'm sorry, it's my private project on private repo. Also I did not manage to isolate the problem, I only know I've experienced this and after setting change I've posted, it did not show up again.

**Comment by mzotter** [comment] 2018-12-17 14:08
HI, I've the same problem.
When I open the datepicker, everything works as it should be.
But when I click previousMonth 2 times, component shows incorrectly. => it happens when the initial DateOne or the empty new Date (to set focusedDate) is on the last asd_month, the hidden one. 

Step 1 - shown correctly:
![bildschirmfoto 2018-12-17 um 14 51 41](https://user-images.githubusercontent.com/45843652/50091761-8114d500-020c-11e9-94fb-1e339ba7b58c.png)

Step 2 - after first click on previousMonth:
![bildschirmfoto 2018-12-17 um 14 51 51](https://user-images.githubusercontent.com/45843652/50091717-680c2400-020c-11e9-850d-bca7e1ae4b57.png)

Step 3 - after second click on previousMonth:
(the whole asd_month with selected DateOne should be the last asd_month (hidden))
![bildschirmfoto 2018-12-17 um 14 51 32](https://user-images.githubusercontent.com/45843652/50091785-94c03b80-020c-11e9-89c4-b82bf9645d77.png)

After that I also get following Error in the Dev Tools console from Chrome:
![bildschirmfoto 2018-12-17 um 15 03 30](https://user-images.githubusercontent.com/45843652/50091946-0dbf9300-020d-11e9-8354-41e7c37641b4.png)

![bildschirmfoto 2018-12-17 um 15 05 02](https://user-images.githubusercontent.com/45843652/50091987-26c84400-020d-11e9-9c64-0307f42a72e6.png)

It can be reproduced on ur Demo site: first DatePicker
http://htmlpreview.github.io/?https://github.com/MikaelEdebro/vue-airbnb-style-datepicker/blob/master/docs/examples.html

**Comment by jeryj** [comment] 2019-02-28 19:17
I encountered this issue in my app, and it was related to another library adding its own `.hidden { display: none; }` CSS. 

I took a look at the source, and here's my guess at what's going on:

`/src/components/AirbnbStyleDatepicker.vue` on line 57 is using `:class="{hidden: monthIndex === 0 || monthIndex > showMonths}"`. It looks like the CSS was updated to BEM though, and this hidden class was missed. I think the datepicker is wanting `asd__month--hidden` instead of `hidden`, like:

`:class="{asd__month--hidden: monthIndex === 0 || monthIndex > showMonths}"`

**Comment by MikaelEdebro** [comment] 2019-03-21 20:45
Hopefully this is fixed in v 2.5.0. Thanks @jeryj for pointing out the missed class.

**Closed by MikaelEdebro** 2019-03-21 20:45 UTC
